version: "3.8"

services:
  #Это конфигурация Docker Compose для службы базы данных MariaDB используемой Seafile.
  seafile-mariadb:
    container_name: seafile-mariadb
    deploy:
      restart_policy:
        condition: always
        delay: 5s
    env_file: mariadb.env
    image: mariadb:latest
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "false"
    shm_size: 256mb
    # ports:
    #   - "3306:3306"
    volumes:
      - "/mnt/docker-volumes/db/seafile-mariadb:/var/lib/mysql"

networks:
  default:
    external: true
    name: $NETWORK
